hungry = input("are you hungry?")
if hungry == "yes":
    print("eat some thing")
    print("eat Pizza")
    print("eat Burger")
    print("eat chiken")
else:
    print("Prepare DevOps")
    print("Prepare GitHub")
    print("Prepare Docker")
    print("Prepare Kubernaties")
    print("Prepare CICD")
    print("Prepare Linux")
    print("Prepare ShellScript")
    print("Prepare BashShell")